import { StyleTemplate } from '../types/caption.types';

export const STYLE_TEMPLATES: StyleTemplate[] = [
  {
    id: 'bold_impact',
    name: 'Bold Impact',
    description: 'High contrast with stroke',
    style: {
      templateId: 'bold_impact',
      fontSize: 48,
      fontFamily: 'Impact, sans-serif',
      color: '#FFFFFF',
      strokeColor: '#000000',
      strokeWidth: 4,
      backgroundColor: null,
      backgroundOpacity: 1,
      animation: 'pop',
      textTransform: 'uppercase',
      fontWeight: 900,
      letterSpacing: 2,
      lineHeight: 1.2,
      textShadow: '4px 4px 0px rgba(0,0,0,0.5)',
      rotation: 0,
    }
  },
  {
    id: 'minimal_clean',
    name: 'Minimal Clean',
    description: 'Simple with background',
    style: {
      templateId: 'minimal_clean',
      fontSize: 36,
      fontFamily: 'Montserrat, sans-serif',
      color: '#FFFFFF',
      strokeColor: null,
      strokeWidth: 0,
      backgroundColor: '#000000',
      backgroundOpacity: 0.7,
      animation: 'fade',
      textTransform: 'none',
      fontWeight: 600,
      letterSpacing: 0,
      lineHeight: 1.4,
      textShadow: null,
      rotation: 0,
    }
  },
  {
    id: 'emphasis_energy',
    name: 'Emphasis Energy',
    description: 'Bold yellow for key moments',
    style: {
      templateId: 'emphasis_energy',
      fontSize: 52,
      fontFamily: 'Bebas Neue, sans-serif',
      color: '#FFD700',
      strokeColor: '#000000',
      strokeWidth: 3,
      backgroundColor: null,
      backgroundOpacity: 1,
      animation: 'bounce',
      textTransform: 'uppercase',
      fontWeight: 700,
      letterSpacing: 3,
      lineHeight: 1.1,
      textShadow: '3px 3px 6px rgba(0,0,0,0.8)',
      rotation: 0,
    }
  },
  {
    id: 'handwritten_casual',
    name: 'Handwritten',
    description: 'Casual and friendly',
    style: {
      templateId: 'handwritten_casual',
      fontSize: 44,
      fontFamily: 'Caveat, cursive',
      color: '#FF6B9D',
      strokeColor: null,
      strokeWidth: 0,
      backgroundColor: null,
      backgroundOpacity: 1,
      animation: 'slide_up',
      textTransform: 'none',
      fontWeight: 700,
      letterSpacing: 0,
      lineHeight: 1.3,
      textShadow: '2px 2px 4px rgba(0,0,0,0.6)',
      rotation: -5,
    }
  },
];

export const DEFAULT_CAPTION_STYLE: StyleTemplate['style'] = {
  templateId: 'minimal_clean',
  fontSize: 36,
  fontFamily: 'Montserrat, sans-serif',
  color: '#FFFFFF',
  strokeColor: null,
  strokeWidth: 0,
  backgroundColor: '#000000',
  backgroundOpacity: 0.7,
  animation: 'fade',
  textTransform: 'none',
  fontWeight: 600,
  letterSpacing: 0,
  lineHeight: 1.4,
  textShadow: null,
  rotation: 0,
};
